#!/bin/bash

# $1: caminho relativo para o documento Markdown

mdfile=$1
mdfile="${mdfile%.*}"

# Remove file extension from mdfile
mdfile="${mdfile%.*}"
pdffile="$mdfile.pdf"

echo $mdfile
brave-browser $pdffile